# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - edot-shop-inventory-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress


      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'edot-shop-inventory-app'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_06BFAF156D234800A4DF5BB2DAAECE4D }}

      - name: Run Migrations and Show Logs
        run: |
          # Install expect to handle the interactive SSH session
          sudo apt-get install -y expect

          # Extract credentials from the publish profile
          USERNAME=$(echo "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" | grep -oP '(?<=userName=")[^"]+')
          PASSWORD=$(echo "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" | grep -oP '(?<=userPWD=")[^"]+')

          # Use expect to automate the SSH session
          expect -c "
            set timeout 60
            spawn az webapp ssh --name 'edot-shop-inventory-app' --resource-group '${{ secrets.AZURE_RESOURCE_GROUP }}'
            expect \"root@\" 
            send \"cd /home/site/wwwroot && php artisan migrate --force\r\"
            expect \"root@\"
            send \"exit\r\"
            expect eof
          "